-- AlterEnum
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_TRANSACTION_CREATED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_TRANSACTION_UPDATED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_TRANSACTION_STATUS_CHANGED';
