export type PropertyState = 'PROPERTY_PENDING' | 'LIVE' | 'SOLD';
export type PropertyStatus = 'draft' | 'active' | 'pending' | 'sold' | 'withdrawn' | 'expired';
export type PropertySource = 'bulk_upload' | 'manual' | 'mls';

export interface BrokerPropertyRow {
  id: string;
  draft_id: string | null;
  org_id: string;
  firm_id: string | null;
  agent_id: string | null;
  mls_number: string | null;
  state: PropertyState;
  status: PropertyStatus;
  is_test: boolean;
  source: PropertySource;
  file_name: string | null;
  address_line: string | null;
  street_number: string | null;
  street_name: string | null;
  street_suffix: string | null;
  city: string | null;
  state_code: string | null;
  zip_code: string | null;
  county: string | null;
  latitude: number | null;
  longitude: number | null;
  bedrooms_total: number | null;
  bathrooms_full: number | null;
  bathrooms_half: number | null;
  bathrooms_total: number | null;
  living_area_sq_ft: number | null;
  lot_size_sq_ft: number | null;
  lot_size_acres: number | null;
  year_built: number | null;
  list_price: number | null;
  original_list_price: number | null;
  public_remarks: string | null;
  private_remarks: string | null;
  showing_instructions: string | null;
  architectural_style: string | null;
  property_type: string | null;
  property_sub_type: string | null;
  parcel_id: string | null;
  garage_spaces: number | null;
  garage_type: string | null;
  construction_materials: string | null;
  foundation_details: string | null;
  exterior_features: string | null;
  interior_features: string | null;
  pool_features: string | null;
  cooling: string | null;
  heating: string | null;
  parking_features: string | null;
  appliances: string | null;
  laundry_features: string | null;
  taxes: number | null;
  flooring: string | null;
  fireplace_features: string | null;
  kitchen_features: string | null;
  primary_suite: string | null;
  roof_type: string | null;
  property_view: string | null;
  water_source: string | null;
  sewer_system: string | null;
  list_price_per_sqft: number | null;
  status_type: string | null;
  geo_area: string | null;
  development: string | null;
  property_id: string | null;
  dom: number | null;
  cdom: number | null;
  community_type: string | null;
  golf_type: string | null;
  gulf_access: string | null;
  canal_width: string | null;
  rear_exposure: string | null;
  lot_description: string | null;
  lot_dimensions: string | null;
  water: string | null;
  sewer: string | null;
  irrigation: string | null;
  boat_dock_info: string | null;
  tax_description: string | null;
  terms: string | null;
  possession: string | null;
  approval: string | null;
  management: string | null;
  master_hoa_fee: number | null;
  condo_fee: number | null;
  special_assessment: number | null;
  other_fee: number | null;
  land_lease: number | null;
  mandatory_club_fee: number | null;
  recreation_lease_fee: number | null;
  total_annual_recurring_fees: number | null;
  total_one_time_fees: number | null;
  office_code: string | null;
  office_name: string | null;
  office_phone: string | null;
  office_address: string | null;
  listing_agent_mls_id: string | null;
  listing_agent_fax: string | null;
  appointment_required: string | null;
  appointment_phone: string | null;
  target_marketing: string | null;
  internet_sites: string | null;
  listing_on_internet: string | null;
  address_on_internet: string | null;
  blogging: string | null;
  avm: string | null;
  listing_broker: string | null;
  legal_description: string | null;
  section_town_range: string | null;
  subdivision: string | null;
  slug: string | null;
  cover_photo_url: string | null;
  validation_summary: Record<string, unknown> | null;
  owner_name: string | null;
  owner_email: string | null;
  owner_phone: string | null;
  additional_fields: Record<string, unknown> | null;
  source_extracted: unknown[] | null;
  source_matches: unknown[] | null;
  listing_agent_name: string | null;
  listing_agent_license: string | null;
  listing_agent_phone: string | null;
  listing_agent_email: string | null;
  listing_office_name: string | null;
  listing_office_phone: string | null;
  listing_office_email: string | null;
  listing_office_license: string | null;
  photos: string[];
  published_at: string | null;
  closed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface PromoteDraftPayload {
  draftId?: string;
  firmId: string;
  agentId?: string;
  source?: PropertySource;
  fileName?: string;
  property: Record<string, any>;
  validationSummary?: Record<string, unknown> | null;
  isTest?: boolean;
}
