-- AlterEnum
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_LISTING_CREATED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_LISTING_UPDATED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_LISTING_STATUS_CHANGED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_LISTING_APPROVAL_REQUESTED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_LISTING_APPROVED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_LISTING_REJECTED';
ALTER TYPE "OrgEventType" ADD VALUE 'ORG_LISTING_CHANGES_REQUESTED';
